### ISSUE TITLE
提交完数据在哪里“查看”

### ISSUE THREAD

**Issue by auroralzone** [PeterH0323/Streamer-Sales#1]
无法找到提交完的商品。似乎没有发挥作用
后台日志：
```
load model begin.
load model end.
```
![image](https://github.com/PeterH0323/Streamer-Sales/assets/42070770/6f4e9e4a-1f38-4939-8296-ff6b4de0c48d)

**Comment by PeterH0323** [comment]
感谢您的关注。

目前我还没搞好商品监管审核机制，所以暂时没开发这个按钮，😂

**Comment by auroralzone** [comment]
好的。怎么可以上传自己的商品呢，比如一个`csv`文件。
有群组一起讨论一下吗？

**Comment by PeterH0323** [comment]
目前页面读取的商品信息是从这个 yaml 中提取的，如果您现在自己尝试的话，可以修改这个 yaml : https://github.com/PeterH0323/Streamer-Sales/blob/main/product_info/product_info.yaml

如果本项目帮到您，可以右上角帮我点个 star~ ⭐⭐ , 您的 star ⭐是我们最大的鼓励，谢啦！

**Comment by auroralzone** [comment]
```md
## xxx空调

【价价】***/*** ***/***
【直播价】***/*** ***/***
【规格】***
【颜色】***
【发货时间】48小时
【售后服务】七天无理由退货
【售后服务】免费送货上门
【售后服务】包邮包安装免人工费
...

### 亮点：
- ***
- ***
- ***
- ***
- ***

### 卖点：
1. ***
2. ***
3. ***
4. ***
5. ***
6. ***
```
外加很多图片。

这些数据如何添加上去呢？有参考吗😂

**Comment by PeterH0323** [comment]
新版本已支持上传商品，同时文档已更新，请查看 :smile:

文档：
https://github.com/PeterH0323/Streamer-Sales/blob/f2bbcd0bc7e0b1e2e16a1b3a873b1f665ff8be86/README.md?plain=1#L525-L548
