### ISSUE TITLE
在Windows WSL Ubuntu 系统中 运行没有报错 但是 不反回内容

### ISSUE THREAD

**Issue by tdouguo** [PeterH0323/Streamer-Sales#10]
系统：Windows 11 专业工作站版
运行子系统：Ubuntu 22.04.3 LTS
环境 Conda: conda 24.5.0
CPU i9 3.2GHz
内存：96G
显卡  4090 24G 1块

在子系统内显卡驱动
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```

完全安装文档安装命令
方案1： 手动下载模型文件到文件夹里面 ，尝试最后运行时无响应
方案2：cloud 项目以后 conda 激活，pip 安装依赖，直接运行，然后在访问以后自动下载模型 全部走完以后 还是到此处 
点击主播讲解 看控制台是发生了 但是无响应

![image](https://github.com/PeterH0323/Streamer-Sales/assets/22972345/51c7def2-da19-460e-8860-4fa590dd0e12)

**Comment by tdouguo** [comment]
补充 ~/.bashrc 以添加的变量
```

export CUDA_HOME=/usr/local/cuda
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH


export HF_ENDPOINT=https://hf-mirror.com
export USING_4BIT=true
export KV_CACHE=0.05
```

**Comment by PeterH0323** [comment]
24G显存有 OOM 的风险，可以设置 `ENABLE_ASR=false` 将 ASR 关闭，同时设置 `KV_CACHE=0.1` ：

```bash
export ENABLE_ASR=false
export KV_CACHE=0.1
```
