### ISSUE TITLE
执行这个  conda env create -f environment.yml 报错 PackagesNotFoundError: The following packages are not available from current channels:

### ISSUE THREAD

**Issue by anstonjie** [PeterH0323/Streamer-Sales#11]
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

**Comment by PeterH0323** [comment]
目前暂不支持 win
