### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:

### ISSUE THREAD

**Issue by pamperherself** [PeterH0323/Streamer-Sales#13]
Streamer-Sales % conda env create -f environment.yml
Channels:
 - pytorch
 - nvidia
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - zstd==1.5.5=hc292b87_0
  - zlib==1.2.13=h5eee18b_0
  - yaml==0.2.5=h7b6447c_0
  - xz==5.4.6=h5eee18b_0
  - wheel==0.41.2=py310h06a4308_0
  - urllib3==2.1.0=py310h06a4308_1
  - torchvision==0.16.2=py310_cu121
  - torchtriton==2.1.0=py310
  - torchaudio==2.1.2=py310_cu121
  - tk==8.6.12=h1ccaba5_0
  - tbb==2021.8.0=hdb19cb5_0
  - sympy==1.12=py310h06a4308_0
  - sqlite==3.41.2=h5eee18b_0
  - setuptools==68.2.2=py310h06a4308_0
  - requests==2.31.0=py310h06a4308_1
  - readline==8.2=h5eee18b_0
  - pyyaml==6.0.1=py310h5eee18b_0
  - pytorch-cuda==12.1=ha16c6d3_5
  - pytorch==2.1.2=py3.10_cuda12.1_cudnn8.9.2_0
  - python==3.10.14=h955ad1f_0
  - pysocks==1.7.1=py310h06a4308_0
  - pip==23.3.1=py310h06a4308_0
  - pillow==10.2.0=py310h5eee18b_0
  - openssl==3.0.13=h7f8727e_0
  - openjpeg==2.4.0=h3ad879b_0
  - openh264==2.1.1=h4ff587b_0
  - numpy-base==1.26.4=py310hb5e798b_0
  - numpy==1.26.4=py310h5f9d8c6_0
  - networkx==3.1=py310h06a4308_0
  - nettle==3.7.3=hbbd107a_1
  - ncurses==6.4=h6a678d5_0
  - mpmath==1.3.0=py310h06a4308_0
  - mpfr==4.0.2=hb69a4c5_1
  - mpc==1.1.0=h10f8cd9_1
  - mkl_random==1.2.4=py310hdb19cb5_0
  - mkl_fft==1.3.8=py310h5eee18b_0
  - mkl-service==2.4.0=py310h5eee18b_1
  - mkl==2023.1.0=h213fc3f_46344
  - markupsafe==2.1.3=py310h5eee18b_0
  - lz4-c==1.9.4=h6a678d5_0
  - llvm-openmp==14.0.6=h9e868ea_0
  - libwebp-base==1.3.2=h5eee18b_0
  - libuuid==1.41.5=h5eee18b_0
  - libunistring==0.9.10=h27cfd23_0
  - libtiff==4.5.1=h6a678d5_0
  - libtasn1==4.19.0=h5eee18b_0
  - libstdcxx-ng==11.2.0=h1234567_1
  - libpng==1.6.39=h5eee18b_0
  - libnvjpeg==12.1.1.14=0
  - libnvjitlink==12.1.105=0
  - libnpp==12.0.2.50=0
  - libjpeg-turbo==2.0.0=h9bf148f_0
  - libidn2==2.3.4=h5eee18b_0
  - libiconv==1.16=h7f8727e_2
  - libgomp==11.2.0=h1234567_1
  - libgcc-ng==11.2.0=h1234567_1
  - libffi==3.4.4=h6a678d5_0
  - libdeflate==1.17=h5eee18b_1
  - libcusparse==12.0.2.55=0
  - libcusolver==11.4.4.55=0
  - libcurand==10.3.5.119=0
  - libcufile==1.9.0.20=0
  - libcufft==11.0.2.4=0
  - libcublas==12.1.0.26=0
  - lerc==3.0=h295c915_0
  - ld_impl_linux-64==2.38=h1181459_1
  - lcms2==2.12=h3be6417_0
  - lame==3.100=h7b6447c_0
  - jpeg==9e=h5eee18b_1
  - jinja2==3.1.3=py310h06a4308_0
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - idna==3.4=py310h06a4308_0
  - gnutls==3.6.15=he1e5248_0
  - gmpy2==2.1.2=py310heeb90bb_0
  - gmp==6.2.1=h295c915_3
  - freetype==2.12.1=h4a9f257_0
  - filelock==3.13.1=py310h06a4308_0
  - ffmpeg==4.3=hf484d3e_0
  - cuda-runtime==12.1.0=0
  - cuda-opencl==12.4.127=0
  - cuda-nvtx==12.1.105=0
  - cuda-nvrtc==12.1.105=0
  - cuda-libraries==12.1.0=0
  - cuda-cupti==12.1.105=0
  - cuda-cudart==12.1.105=0
  - certifi==2024.2.2=py310h06a4308_0
  - ca-certificates==2024.3.11=h06a4308_0
  - bzip2==1.0.8=h5eee18b_5
  - brotli-python==1.0.9=py310h6a678d5_7
  - blas==1.0=mkl
  - _openmp_mutex==5.1=1_gnu
  - _libgcc_mutex==0.1=main

Current channels:

  - https://conda.anaconda.org/pytorch/osx-arm64
  - https://conda.anaconda.org/nvidia/osx-arm64
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/r/osx-arm64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

### macos 环境, 怎么解决呢, 第一步创建依赖环境就不行

**Comment by PeterH0323** [comment]
我的开发机器是 Linux
