### ISSUE TITLE
如何切换语音？

### ISSUE THREAD

**Issue by piwawa** [PeterH0323/Streamer-Sales#15]
怎么切换不同的语音模型或者使用 Azure 语音来合成？以支持不同语言输出

**Comment by PeterH0323** [comment]
支持更换 TTS 的微调模型，请参考文档：https://github.com/PeterH0323/Streamer-Sales#%E5%A6%82%E4%BD%95%E6%9B%BF%E6%8D%A2%E8%87%AA%E5%B7%B1%E7%9A%84-tts

如果您需要使用商用 API，可以根据自己的业务自行修改
