### ISSUE TITLE
前端服务引入大小写错误

### ISSUE THREAD

**Issue by piaoyaoi** [PeterH0323/Streamer-Sales#27]
import barChartComponent from '@/components/BarChartComponent.vue'
import lineChartComponent from '@/components/LineChartComponent.vue'
BarChartComponent和LineChartComponent首字母应该是小写的
在/root/Streamer-Sales/frontend/src/views/home/HomeView.vue文件里

**Comment by PeterH0323** [comment]
Fixed，感谢您的指出
