### ISSUE TITLE
启动时报这个是什么问题？ImportError: cannot import name 'RAG_RETRIEVER' from 'utils.model_loader'

### ISSUE THREAD

**Issue by Bruceywj** [PeterH0323/Streamer-Sales#9]
2024-07-08 06:57:53.976 Uncaught app exception
Traceback (most recent call last):
  File "/home/ef/anaconda3/envs/streamer-sales/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/home/ef/Streamer-Sales/app.py", line 33, in <module>
    from utils.model_loader import RAG_RETRIEVER  # isort:skip
ImportError: cannot import name 'RAG_RETRIEVER' from 'utils.model_loader' (/home/ef/Streamer-Sales/utils/model_loader.py)
/home/ef/anaconda3/envs/streamer-sales/lib/python3.10/site-packages/streamlit/watcher/local_sources_watcher.py:196: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  lambda m: [p for p in m.__path__._path],

**Comment by PeterH0323** [comment]
刷新下页面就可以解决了，后续版本会把这个修复

**Comment by Bruceywj** [comment]
谢谢，刷新后，可以继续了。
大佬，有技术群可以拉我进来吗？感谢
